// bun:test smoke tests for the TS wrapper's wasm loader + bare-core decoders
// (FDR-0007). Network-free: they drive build/papi-client.wasm directly (path via
// $PAPI_CLIENT_WASM, set by `just test-ts`); the fetch-based Client is exercised
// against a live domain, not here.

import { test, expect } from "bun:test";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  decodeProfiles,
  decodeRepos,
  decodeDocument,
  verifyDocument,
  Client,
} from "./papi.ts";

const fixture = (name: string): string =>
  readFileSync(
    fileURLToPath(new URL(`./testdata/${name}`, import.meta.url)),
    "utf8",
  );

test("decodeProfiles: NixOS pair + non-NixOS home", () => {
  const body =
    `{"data":[` +
    `{"id":"framework-laptop","flakeref":"github:amarbel-llc/eng#nixosConfigurations.framework-laptop",` +
    `"home_flakeref":"github:amarbel-llc/eng#homeConfigurations.framework-laptop","kind":"nixos-configuration"},` +
    `{"id":"dev","flakeref":"github:amarbel-llc/eng#homeConfigurations.dev","kind":"home-configuration"}` +
    `],"meta":{"type":"profiles","count":2}}`;
  const ps = decodeProfiles(body);
  expect(ps.length).toBe(2);
  expect(ps[0].id).toBe("framework-laptop");
  expect(ps[0].home_flakeref).toBeTruthy();
  expect(ps[1].home_flakeref ?? "").toBe("");
});

test("decodeRepos", () => {
  const body = `{"data":[{"name":"papi","url":"https://github.com/amarbel-llc/papi","owner":"amarbel-llc"}],"meta":{"count":1}}`;
  const rs = decodeRepos(body);
  expect(rs.length).toBe(1);
  expect(rs[0].name).toBe("papi");
});

test("decodeDocument unwraps the envelope", () => {
  const doc = decodeDocument(
    `{"data":{"version":"papi/v0","profiles":[{"id":"dev","flakeref":"github:x#homeConfigurations.dev","kind":"home-configuration"}]},"meta":{}}`,
  );
  expect(doc.version).toBe("papi/v0");
  expect(doc.profiles?.length).toBe(1);
});

test("verifyDocument: unsigned is not authentic", () => {
  const res = verifyDocument(`{"data":{"version":"papi/v0"},"meta":{}}`, []);
  expect(res.authentic).toBe(false);
});

test("Client.for normalizes a bare domain to an https base", () => {
  expect(Client.for("linenisgreat.com").base).toBe("https://linenisgreat.com");
  expect(Client.for("https://api.example.test/x").base).toBe(
    "https://api.example.test",
  );
});

// --- §10 verify of a real signed /papi document through the wasm core (FDR-0007
// promotion bar). The fixture (clients/ts/testdata/signed-papi.*) is generated by
// `just debug-signed-doc`; its key is trusted only via the published id. ---

test("verifyDocument: a real signed /papi document is authentic", () => {
  const body = fixture("signed-papi.json");
  const pubid = fixture("signed-papi.pubid.txt").trim();
  const res = verifyDocument(body, [pubid]);
  expect(res.authentic).toBe(true);
  expect(res.checks.some((c) => c.ok)).toBe(true);
});

test("verifyDocument: wrong published id is not authentic (unverifiable)", () => {
  const body = fixture("signed-papi.json");
  const res = verifyDocument(body, [
    "piggy-piv_auth-v1@ssh_ecdsa_nistp256_pub-deadbeef",
  ]);
  expect(res.authentic).toBe(false);
});

test("verifyDocument: tampered body is not authentic (signed-but-invalid)", () => {
  const pubid = fixture("signed-papi.pubid.txt").trim();
  const tampered = fixture("signed-papi.json").replace(
    '"fixture"',
    '"attacker"',
  );
  const res = verifyDocument(tampered, [pubid]);
  expect(res.authentic).toBe(false);
});
